#用debug 可以看哪些依赖生效了
#debug: true
#
person:
  name: haha${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2020/12/12
  hello: ppp
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hello:hello}_旺财
    age: 3

server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
  port: 8084
spring:
  on-profiles: dev

---
server:
  port: 8083
spring:
  on-profiles: test